In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px # to plot the time series plot
from sklearn import metrics # for the evaluation
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
import tensorflow as tf 
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
from pandas import read_csv
from pandas import DataFrame
import os
import datetime
import IPython
import IPython.display

from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
import pandas as pd
from pandas import read_csv
import numpy as np
import random
from pandas import DataFrame
from numpy import concatenate
from pandas import concat
from scipy.stats import randint as sp_randint
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, explained_variance_score 


import matplotlib.patches as mpatches
import matplotlib.pylab as plt
import matplotlib as mpl
%matplotlib inline
plt.rcParams['figure.figsize'] = (16, 7)
plt.style.use('fast')
mpl.rcParams['figure.figsize'] = (8, 6)
mpl.rcParams['axes.grid'] = False
from sklearn.neural_network import MLPRegressor


np.random.seed(123) # for reproducibility
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Activation,Flatten
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from tensorflow import keras
from scikeras.wrappers import KerasClassifier, KerasRegressor
import keras_tuner

In [2]:
# CARGAR LA BASE DE DATOS
from pandas import read_csv
datos = read_csv('Lebrija_Lags.csv', encoding='latin-1', sep=";")

datos.columns

Index(['Municipio', 'Año', 'Semana_Epi', 'Casos_Dengue',
       'Temp_Seca_Max_Dia_Prom', 'Temp_Seca_Max_Dia_Prom_1',
       'Temp_Seca_Max_Dia_Prom_2', 'Temp_Seca_Max_Dia_Prom_3',
       'Temp_Seca_Max_Dia_Prom_4', 'Temp_Seca_Max_Dia_Prom_5',
       'Temp_Seca_Max_Dia_Prom_6', 'Temp_Seca_Max_Sem', 'Temp_Seca_Max_Sem_1',
       'Temp_Seca_Max_Sem_2', 'Temp_Seca_Max_Sem_3', 'Temp_Seca_Max_Sem_4',
       'Temp_Seca_Max_Sem_5', 'Temp_Seca_Max_Sem_6', 'Temp_Seca_Min_Dia_Prom',
       'Temp_Seca_Min_Dia_Prom_1', 'Temp_Seca_Min_Dia_Prom_2',
       'Temp_Seca_Min_Dia_Prom_3', 'Temp_Seca_Min_Dia_Prom_4',
       'Temp_Seca_Min_Dia_Prom_5', 'Temp_Seca_Min_Dia_Prom_6',
       'Temp_Seca_Min_Sem', 'Temp_Seca_Min_Sem_1', 'Temp_Seca_Min_Sem_2',
       'Temp_Seca_Min_Sem_3', 'Temp_Seca_Min_Sem_4', 'Temp_Seca_Min_Sem_5',
       'Temp_Seca_Min_Sem_6', 'Prom_Dia_Preci', 'Prom_Dia_Preci_1',
       'Prom_Dia_Preci_2', 'Prom_Dia_Preci_3', 'Prom_Dia_Preci_4',
       'Prom_Dia_Preci_5', 'Prom_Dia_Preci_6', 'Total_Preci_Sem',
       'Total_Preci_Sem_1', 'Total_Preci_Sem_2', 'Total_Preci_Sem_3',
       'Total_Preci_Sem_4', 'Total_Preci_Sem_5', 'Total_Preci_Sem_6',
       'Temp_Max_Dia_Prom', 'Temp_Max_Dia_Prom_1', 'Temp_Max_Dia_Prom_2',
       'Temp_Max_Dia_Prom_3', 'Temp_Max_Dia_Prom_4', 'Temp_Max_Dia_Prom_5',
       'Temp_Max_Dia_Prom_6', 'Temp_Max_Sem', 'Temp_Max_Sem_1',
       'Temp_Max_Sem_2', 'Temp_Max_Sem_3', 'Temp_Max_Sem_4', 'Temp_Max_Sem_5',
       'Temp_Max_Sem_6', 'Temp_Min_Dia_Prom', 'Temp_Min_Dia_Prom_1',
       'Temp_Min_Dia_Prom_2', 'Temp_Min_Dia_Prom_3', 'Temp_Min_Dia_Prom_4',
       'Temp_Min_Dia_Prom_5', 'Temp_Min_Dia_Prom_6', 'Temp_Min_Sem',
       'Temp_Min_Sem_1', 'Temp_Min_Sem_2', 'Temp_Min_Sem_3', 'Temp_Min_Sem_4',
       'Temp_Min_Sem_5', 'Temp_Min_Sem_6'],
      dtype='object')

In [3]:
# Dropping the id and date columns
datos = datos.drop(['Municipio', 'Año', 'Semana_Epi', 'Temp_Seca_Max_Dia_Prom_1','Temp_Seca_Max_Dia_Prom_2', 
                    'Temp_Seca_Max_Dia_Prom_3','Temp_Seca_Max_Dia_Prom_4', 'Temp_Seca_Max_Dia_Prom_5',
                    'Temp_Seca_Max_Dia_Prom_6', 'Temp_Seca_Max_Sem_1','Temp_Seca_Max_Sem_2', 'Temp_Seca_Max_Sem_3', 
                    'Temp_Seca_Max_Sem_4','Temp_Seca_Max_Sem_5', 'Temp_Seca_Max_Sem_6', 'Temp_Seca_Min_Dia_Prom_1', 
                    'Temp_Seca_Min_Dia_Prom_2', 'Temp_Seca_Min_Dia_Prom_3', 'Temp_Seca_Min_Dia_Prom_4',
                    'Temp_Seca_Min_Dia_Prom_5', 'Temp_Seca_Min_Dia_Prom_6', 'Temp_Seca_Min_Sem_1', 'Temp_Seca_Min_Sem_2',
                    'Temp_Seca_Min_Sem_3', 'Temp_Seca_Min_Sem_4', 'Temp_Seca_Min_Sem_5', 'Temp_Seca_Min_Sem_6', 
                    'Prom_Dia_Preci_1','Prom_Dia_Preci_2', 'Prom_Dia_Preci_3', 'Prom_Dia_Preci_4','Prom_Dia_Preci_5', 
                    'Prom_Dia_Preci_6','Total_Preci_Sem_1', 'Total_Preci_Sem_2', 'Total_Preci_Sem_3','Total_Preci_Sem_4', 
                    'Total_Preci_Sem_5', 'Total_Preci_Sem_6', 'Temp_Max_Dia_Prom_1', 'Temp_Max_Dia_Prom_2',
                    'Temp_Max_Dia_Prom_3', 'Temp_Max_Dia_Prom_4', 'Temp_Max_Dia_Prom_5','Temp_Max_Dia_Prom_6',
                    'Temp_Max_Sem_1','Temp_Max_Sem_2', 'Temp_Max_Sem_3', 'Temp_Max_Sem_4', 'Temp_Max_Sem_5',
                    'Temp_Max_Sem_6', 'Temp_Min_Dia_Prom_1','Temp_Min_Dia_Prom_2', 'Temp_Min_Dia_Prom_3', 
                    'Temp_Min_Dia_Prom_4','Temp_Min_Dia_Prom_5', 'Temp_Min_Dia_Prom_6',
                    'Temp_Min_Sem_1', 'Temp_Min_Sem_2', 'Temp_Min_Sem_3', 'Temp_Min_Sem_4',
                    'Temp_Min_Sem_5', 'Temp_Min_Sem_6'],axis=1)
datos.columns

Index(['Casos_Dengue', 'Temp_Seca_Max_Dia_Prom', 'Temp_Seca_Max_Sem',
       'Temp_Seca_Min_Dia_Prom', 'Temp_Seca_Min_Sem', 'Prom_Dia_Preci',
       'Total_Preci_Sem', 'Temp_Max_Dia_Prom', 'Temp_Max_Sem',
       'Temp_Min_Dia_Prom', 'Temp_Min_Sem'],
      dtype='object')

In [4]:
train_size = int(len(datos) * 0.7)
test_size = len(datos) - train_size
train, test = datos.iloc[0:train_size], datos.iloc[train_size:len(datos)]
print(len(train), len(test))

291 125

In [5]:
f_transformer = MinMaxScaler(feature_range=(0, 1))
f_columns = ['Casos_Dengue', 'Temp_Seca_Max_Dia_Prom', 'Temp_Seca_Max_Sem', 'Temp_Seca_Min_Dia_Prom', 'Temp_Seca_Min_Sem',
             'Prom_Dia_Preci','Total_Preci_Sem', 'Temp_Max_Dia_Prom', 'Temp_Max_Sem', 'Temp_Min_Dia_Prom', 'Temp_Min_Sem']

f_transformer = f_transformer.fit(train[f_columns].to_numpy())
train.loc[:, f_columns] = f_transformer.transform(train[f_columns].to_numpy())
train.head()

,Casos_Dengue,Temp_Seca_Max_Dia_Prom,Temp_Seca_Max_Sem,Temp_Seca_Min_Dia_Prom,Temp_Seca_Min_Sem,Prom_Dia_Preci,Total_Preci_Sem,Temp_Max_Dia_Prom,Temp_Max_Sem,Temp_Min_Dia_Prom,Temp_Min_Sem
0,0.142857,0.400000,0.457143,0.314286,0.409091,0.000000,0.000000,0.419048,0.361111,0.103550,0.119048
1,0.285714,0.215385,0.242857,0.228571,0.363636,0.070734,0.070624,0.185714,0.152778,0.310651,0.380952
2,0.428571,0.292308,0.371429,0.371429,0.545455,0.036813,0.036814,0.347619,0.388889,0.349112,0.380952
3,0.142857,0.369231,0.457143,0.485714,0.613636,0.090455,0.090533,0.374603,0.361111,0.479290,0.523810
4,0.000000,0.215385,0.171429,0.085714,0.181818,0.000263,0.000376,0.220635,0.138889,0.106509,0.142857

In [6]:
train.describe()

,Casos_Dengue,Temp_Seca_Max_Dia_Prom,Temp_Seca_Max_Sem,Temp_Seca_Min_Dia_Prom,Temp_Seca_Min_Sem,Prom_Dia_Preci,Total_Preci_Sem,Temp_Max_Dia_Prom,Temp_Max_Sem,Temp_Min_Dia_Prom,Temp_Min_Sem
count,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000
mean,0.234168,0.395982,0.400982,0.468729,0.546001,0.105095,0.105131,0.432024,0.384021,0.453171,0.487072
std,0.230215,0.161931,0.171578,0.183960,0.170498,0.134610,0.134866,0.157443,0.159121,0.179640,0.163243
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.284615,0.285714,0.342857,0.409091,0.020905,0.020849,0.309524,0.277778,0.331361,0.380952
50%,0.142857,0.400000,0.400000,0.457143,0.545455,0.060479,0.060481,0.439683,0.388889,0.431953,0.476190
75%,0.428571,0.507692,0.485714,0.571429,0.670455,0.128057,0.127348,0.528571,0.486111,0.550296,0.595238
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
dengue_transformer = MinMaxScaler(feature_range=(0, 1))
dengue_transformer = dengue_transformer.fit(train[['Casos_Dengue']])
train['Casos_Dengue'] = dengue_transformer.transform(train[['Casos_Dengue']])
train['Casos_Dengue'].head()

0    0.142857
1    0.285714
2    0.428571
3    0.142857
4    0.000000
Name: Casos_Dengue, dtype: float64

In [8]:
test.loc[:, f_columns] = f_transformer.transform(test[f_columns].to_numpy())
test.head()

,Casos_Dengue,Temp_Seca_Max_Dia_Prom,Temp_Seca_Max_Sem,Temp_Seca_Min_Dia_Prom,Temp_Seca_Min_Sem,Prom_Dia_Preci,Total_Preci_Sem,Temp_Max_Dia_Prom,Temp_Max_Sem,Temp_Min_Dia_Prom,Temp_Min_Sem
291,0.714286,0.415385,0.514286,0.371429,0.318182,0.518012,0.518032,0.474603,0.513889,0.420118,0.333333
292,0.857143,0.492308,0.485714,0.457143,0.500000,0.037602,0.037566,0.485714,0.333333,0.420118,0.380952
293,1.000000,0.461538,0.457143,0.371429,0.500000,0.022088,0.022164,0.444444,0.361111,0.369822,0.476190
294,0.428571,0.415385,0.257143,0.428571,0.590909,0.126216,0.126221,0.428571,0.291667,0.399408,0.523810
295,0.142857,0.338462,0.342857,0.400000,0.545455,0.092296,0.092412,0.355556,0.305556,0.369822,0.476190

In [9]:
test['Casos_Dengue'] = dengue_transformer.transform(test[['Casos_Dengue']])
test['Casos_Dengue'].head()

291    0.714286
292    0.857143
293    1.000000
294    0.428571
295    0.142857
Name: Casos_Dengue, dtype: float64

In [10]:
def create_dataset(X, y, time_steps):
    Xs, ys = [], []
    for i in range(len(X) - time_steps):
        v = X.iloc[i:(i + time_steps)].values
        Xs.append(v)
        ys.append(y.iloc[i + time_steps])
    return np.array(Xs), np.array(ys)

In [11]:
time_steps = 10
# reshape to [samples, time_steps, n_features]
X_train, y_train = create_dataset(train, train.Casos_Dengue, time_steps)
X_test, y_test = create_dataset(test, test.Casos_Dengue, time_steps)
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape )

(281, 10, 11) (281,) (115, 10, 11) (115,)

In [12]:
from tensorflow.keras.layers import InputLayer

def LSTM_model(neuronas,
               dropout_rate,
               num_layers,
               activation = 'relu',
               init_mode='uniform',
              ):
    
    model = keras.Sequential()
    
    # CAPA DE ENTRADA
    model.add(keras.layers.InputLayer(input_shape=(X_train.shape[1], X_train.shape[2])))
    
    
    #CAPAS INTERMEDIAS
    for i in range(num_layers):
        model.add(keras.layers.LSTM(units=neuronas,
                                    activation=activation,
                                    return_sequences = True,
                                    dropout=dropout_rate,
                                    kernel_initializer=init_mode))
        
        
    #CAPA DE SALIDA
    model.add(keras.layers.Dense(1, activation="linear"))
    
    #COMPILACIÓN DEL MODELO
    model.compile(optimizer='adam', loss = 'mse', metrics = ['mse'])
    
    return model

In [13]:
#HIPERPARÁMETROS

neuronas = [50, 70, 100]
activation = ['sigmoid','relu', 'tanh']
init_mode = ['uniform', 'normal', 'zero']
num_layers = [3, 5, 7]
dropout_rate = [0.1, 0.3, 0.5]

#optimizer = ['adam', 'sgd', 'rmsprop']
#batch_size = [40, 60, 80]
#epochs = [10, 50, 100]
#momentum = [0.2, 0.4, 0.5]

param_grid = dict(model__neuronas=neuronas,
                  model__activation=activation,
                  model__init_mode=init_mode,
                  model__dropout_rate=dropout_rate,
                  model__num_layers=num_layers)
                  #batch_size=batch_size,
                  #epochs=epochs,
                  #optimizer__momentum=momentum

In [14]:
model =  KerasRegressor(model=LSTM_model, verbose=0)

rs = RandomizedSearchCV(estimator=model, param_distributions=param_grid, scoring='neg_mean_squared_error',
                        n_jobs=-1, cv=5, n_iter=20, verbose=0,random_state = 123, return_train_score = True)

In [15]:
fitted_model = rs.fit(X_train, y_train)

In [16]:
resultados = pd.DataFrame(fitted_model.cv_results_)
resultados.filter(regex = '(param.*|mean_t|std_t)')\
    .drop(columns = 'params')\
    .sort_values('mean_test_score', ascending = False)\
    .head(10)

,param_model__num_layers,param_model__neuronas,param_model__init_mode,param_model__dropout_rate,param_model__activation,mean_test_score,std_test_score,mean_train_score,std_train_score
0,3,100,uniform,0.5,tanh,NaN,NaN,NaN,NaN
1,5,50,zero,0.1,sigmoid,NaN,NaN,NaN,NaN
2,3,100,normal,0.5,relu,NaN,NaN,NaN,NaN
3,5,50,uniform,0.3,tanh,NaN,NaN,NaN,NaN
4,5,70,uniform,0.3,sigmoid,NaN,NaN,NaN,NaN
5,5,50,uniform,0.1,tanh,NaN,NaN,NaN,NaN
6,7,70,uniform,0.3,tanh,NaN,NaN,NaN,NaN
7,7,100,zero,0.5,sigmoid,NaN,NaN,NaN,NaN
8,5,50,normal,0.1,relu,NaN,NaN,NaN,NaN
9,3,100,zero,0.1,sigmoid,NaN,NaN,NaN,NaN

In [17]:
print("Best: %f using %s" % (fitted_model.best_score_, fitted_model.best_params_))

Best: nan using {'model__num_layers': 3, 'model__neuronas': 100, 'model__init_mode': 'uniform', 'model__dropout_rate': 0.5, 'model__activation': 'tanh'}